from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    PageBreak
)
from reportlab.lib.styles import (
    getSampleStyleSheet
)
from datetime import datetime

def build_report(
    analysis,
    query,
    output_path
):

    doc = SimpleDocTemplate(
        output_path
    )

    styles = (
        getSampleStyleSheet()
    )

    content = []

    content.append(
        Paragraph(
            "Investigative Intelligence Report",
            styles["Title"]
        )
    )

    content.append(
        Paragraph(
            f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
            styles["BodyText"]
        )
    )

    content.append(
        Spacer(1, 6)
    )

    content.append(
        Paragraph(
            f"Query: {query}",
            styles["BodyText"]
        )
    )

    content.append(
        Spacer(1, 12)
    )

    content.append(
        Paragraph(
            "Executive Summary",
            styles["Heading2"]
        )
    )

    content.append(
        Paragraph(
            analysis["summary"],
            styles["BodyText"]
        )
    )

    content.append(
        Spacer(1, 12)
    )

    content.append(
        Paragraph(
            "Key Findings",
            styles["Heading2"]
        )
    )

    for finding in analysis.get(
        "key_findings",
        []
    ):

        content.append(
            Paragraph(
                "■ "
                + finding["finding"],
                styles["BodyText"]
            )
        )

        for source in finding.get(
            "sources",
            []
        ):

            content.append(
                Paragraph(
                    f"Source: "
                    f"{source['filename']} "
                    f"(chunk "
                    f"{source['chunk_index']})",
                    styles["Italic"]
                )
            )

        content.append(
            Spacer(1, 6)
        )

        content.append(
            Paragraph(
                "• "
                + finding["finding"],
                styles["BodyText"]
            )
        )

    content.append(
        Spacer(1, 12)
    )

    if analysis.get(
        "timeline"
    ):

        content.append(
            Paragraph(
                "Timeline",
                styles["Heading2"]
            )
        )

        for event in analysis[
            "timeline"
        ]:

            content.append(
                Paragraph(
                    f"{event['date']}",
                    styles["Heading3"]
                )
            )

            content.append(
                Paragraph(
                    event["event"],
                    styles["BodyText"]
                )
            )

            for source in event.get(
                "sources",
                []
            ):

                content.append(
                    Paragraph(
                        f"Source: "
                        f"{source['filename']}",
                        styles["Italic"]
                    )
                )

            content.append(
                Spacer(1, 8)
            )

    content.append(
        Paragraph(
            "Important Entities",
            styles["Heading2"]
        )
    )

    for entity in analysis.get(
        "important_entities",
        []
    ):

        content.append(
            Paragraph(
                f"• {entity}",
                styles["BodyText"]
            )
        )

    content.append(
        Spacer(1, 12)
    )

    content.append(
        Paragraph(
            "Uncertainties",
            styles["Heading2"]
        )
    )

    for item in analysis.get(
        "uncertainties",
        []
    ):

        content.append(
            Paragraph(
                f"• {item}",
                styles["BodyText"]
            )
        )

    doc.build(content)

    content.append(
        Spacer(1, 12)
    )

    content.append(
        Paragraph(
            "Source Index",
            styles["Heading2"]
        )
    )

    seen = set()

    for finding in analysis.get(
        "key_findings",
        []
    ):

        for source in finding.get(
            "sources",
            []
        ):

            filename = (
                source["filename"]
            )

            if filename in seen:
                continue

            seen.add(
                filename
            )

            content.append(
                Paragraph(
                    filename,
                    styles["BodyText"]
                )
            )

    content.append(
        Spacer(1, 20)
    )

    content.append(
        Paragraph(
            "Generated by Evidence Archive",
            styles["Italic"]
        )
    )    